version: '3.8'

services:
  db:
    image: mlp.jpg
    container_name: mylittleponyvefurinn_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mylittleponyvefurinn
    ports:
      - "5432:5432"
    volumes:
      -pgdata:/var/lib/postgresql/data
      -./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: